services:
  server:
    build: martinator-api
    ports:
      - 8080:8080
    depends_on:
      - db

  migrations:
    build:
      context: martinator-api
      dockerfile: migrations.Dockerfile
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
